In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')

In [3]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [4]:
dataframe.shape

(1313, 6)

In [5]:
dataframe.isna().mean() * 100

Name         0.000000
PClass       0.000000
Age         42.421935
Sex          0.000000
Survived     0.000000
SexCode      0.000000
dtype: float64

In [6]:
dataframe.dtypes

Name         object
PClass       object
Age         float64
Sex          object
Survived      int64
SexCode       int64
dtype: object

In [7]:
dataframe.tail()

Name PClass   Age   Sex  Survived  SexCode
1308      Zakarian, Mr Artun    3rd  27.0  male         0        0
1309  Zakarian, Mr Maprieder    3rd  26.0  male         0        0
1310        Zenni, Mr Philip    3rd  22.0  male         0        0
1311        Lievens, Mr Rene    3rd  24.0  male         0        0
1312          Zimmerman, Leo    3rd  29.0  male         0        0

In [11]:
df = dataframe.set_index('Name')

In [12]:
df.head()

PClass    Age     Sex  Survived  \
Name                                                                            
Allen, Miss Elisabeth Walton                     1st  29.00  female         1   
Allison, Miss Helen Loraine                      1st   2.00  female         0   
Allison, Mr Hudson Joshua Creighton              1st  30.00    male         0   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female         0   
Allison, Master Hudson Trevor                    1st   0.92    male         1   

                                               SexCode  
Name                                                    
Allen, Miss Elisabeth Walton                         1  
Allison, Miss Helen Loraine                          1  
Allison, Mr Hudson Joshua Creighton                  0  
Allison, Mrs Hudson JC (Bessie Waldo Daniels)        1  
Allison, Master Hudson Trevor                        0

In [13]:
df.columns

Index(['PClass', 'Age', 'Sex', 'Survived', 'SexCode'], dtype='object')

In [18]:
df.index.name

'Name'

In [20]:
df.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [21]:
df.describe().T

count       mean        std   min   25%   50%   75%   max
Age        756.0  30.397989  14.259049  0.17  21.0  28.0  39.0  71.0
Survived  1313.0   0.342727   0.474802  0.00   0.0   0.0   1.0   1.0
SexCode   1313.0   0.351866   0.477734  0.00   0.0   0.0   1.0   1.0

In [22]:
df['Survived'].unique()

array([1, 0])

In [24]:
for i in df.columns:
    print(f'{i}\n{df[i].unique()}\n---------')

PClass
['1st' '2nd' '*' '3rd']
---------
Age
[29.    2.   30.   25.    0.92 47.   63.   39.   58.   71.   19.     nan
 50.   24.   36.   37.   26.   28.   45.   22.   41.   48.   44.   59.
 60.   53.   33.   14.   11.   49.   46.   27.   31.   64.   55.   70.
 69.   38.   17.    4.   23.   35.   54.   21.   52.   16.   51.   42.
 40.   15.   65.   18.   56.   43.   61.   13.   34.    6.   57.   32.
 62.   67.   20.    1.   12.    0.83  8.    7.    3.    0.8   9.    5.
  0.33  0.17 10.    1.5 ]
---------
Sex
['female' 'male']
---------
Survived
[1 0]
---------
SexCode
[1 0]
---------


In [28]:
df.describe(percentiles=[0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99, 1])

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
1%       1.000000     0.000000     0.000000
10%     16.000000     0.000000     0.000000
20%     20.000000     0.000000     0.000000
30%     22.000000     0.000000     0.000000
40%     25.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
60%     32.000000     0.000000     0.000000
70%     36.000000     1.000000     1.000000
80%     43.000000     1.000000     1.000000
90%     50.000000     1.000000     1.000000
99%     64.450000     1.000000     1.000000
100%    71.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [29]:
df[df['SexCode'] == 1].head()

PClass   Age     Sex  Survived  \
Name                                                                           
Allen, Miss Elisabeth Walton                     1st  29.0  female         1   
Allison, Miss Helen Loraine                      1st   2.0  female         0   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female         0   
Andrews, Miss Kornelia Theodosia                 1st  63.0  female         1   
Appleton, Mrs Edward Dale (Charlotte Lamson)     1st  58.0  female         1   

                                               SexCode  
Name                                                    
Allen, Miss Elisabeth Walton                         1  
Allison, Miss Helen Loraine                          1  
Allison, Mrs Hudson JC (Bessie Waldo Daniels)        1  
Andrews, Miss Kornelia Theodosia                     1  
Appleton, Mrs Edward Dale (Charlotte Lamson)         1

In [30]:
df[df['SexCode'] == 1].shape

(462, 5)

In [37]:
name = ['aparna', 'pankaj', 'sudhir', 'Geeku']
deg = ['MBA', 'BCA', 'M.Tech', 'MBA']
scr = [90, 40, 80, 98]

In [38]:
dict = {'name': name, 'degree': deg, 'score': scr}
df = pd.DataFrame(dict)

In [33]:
df.head()

name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [34]:
df.to_csv('lecture_2.csv')

In [1]:
from sklearn.datasets import make_regression, make_classification

In [69]:
features, target, coefficients = make_regression(n_samples=100, n_features=3,
                                            n_informative=3, n_targets=1, noise=0.0,
                                            coef=True, random_state=1)

In [70]:
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]


In [71]:
type(target)

numpy.ndarray

In [72]:
df_features = pd.DataFrame(data=features)
df_features.head()

0         1         2
0  1.293226 -0.617362 -0.110447
1 -2.793085  0.366332  1.937529
2  0.801861 -0.186570  0.046567
3  0.129102  0.502741  1.616950
4 -0.691661 -0.687173 -0.396754

In [73]:
df_target = pd.DataFrame(data=target)
df_target.head()

0
0  -10.378660
1   25.512450
2   19.677056
3  149.502054
4 -121.652109

In [76]:
df = pd.concat([df_features, df_target], axis=1)

In [77]:
df.head()

0         1         2           0
0  1.293226 -0.617362 -0.110447  -10.378660
1 -2.793085  0.366332  1.937529   25.512450
2  0.801861 -0.186570  0.046567   19.677056
3  0.129102  0.502741  1.616950  149.502054
4 -0.691661 -0.687173 -0.396754 -121.652109

In [86]:
coefficients

array([44.19042807, 98.97517077, 58.15774073])

In [79]:
features, target = make_classification(n_samples=100, n_features=3, n_informative=3,
                                        n_redundant=0, n_classes=2, weights=[.25, .75], random_state=1)

In [80]:
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]
Target Vector
 [1 0 0]


In [81]:
df_features = pd.DataFrame(features)
df_features.head()

0         1         2
0  1.063548 -1.426322  1.021632
1  0.231570  1.495353  0.332516
2  0.159730  0.835335 -0.408696
3 -0.706121 -1.032810  1.394780
4  0.844490 -0.619972  1.087911

In [82]:
df_target = pd.DataFrame(target)
df_target.head()

0
0  1
1  0
2  0
3  1
4  1

In [87]:
df = pd.concat([df_features, df_target], axis=1)

In [88]:
df.head()

0         1         2  0
0  1.063548 -1.426322  1.021632  1
1  0.231570  1.495353  0.332516  0
2  0.159730  0.835335 -0.408696  0
3 -0.706121 -1.032810  1.394780  1
4  0.844490 -0.619972  1.087911  1

In [89]:
features, target, coefficients = make_regression(n_samples=100, n_features=3,
                                            n_informative=2, n_targets=1, noise=0.0,
                                            coef=True, random_state=1)

In [90]:
features[:3]

array([[-1.1191154 , -0.89055558,  1.9560789 ],
       [ 0.84616065,  0.31515939, -0.85951594],
       [ 0.58281521,  0.04221375, -1.10061918]])

In [91]:
target[:3]

array([-104.43925569,   63.13782001,   35.76065963])

In [93]:
coefficients

array([58.15774073, 44.19042807,  0.        ])

In [94]:
df_features = pd.DataFrame(data=features, columns=['Col1', 'Col2', 'Col3'])
df_target = pd.DataFrame(data=target, columns=['Target'])

df = pd.concat([df_features, df_target], axis=1)


In [95]:
df.corr()

Col1      Col2      Col3    Target
Col1    1.000000 -0.109183 -0.061937  0.746055
Col2   -0.109183  1.000000 -0.018778  0.580447
Col3   -0.061937 -0.018778  1.000000 -0.063318
Target  0.746055  0.580447 -0.063318  1.000000

In [2]:
features, target, coefficients = make_regression(n_samples=100, n_features=3,
                                            n_informative=3, n_targets=1, noise=0.0,
                                            coef=True, random_state=1)

In [20]:
df = pd.DataFrame(data=features)
df['Target'] = target

In [22]:
df.head()

0         1         2      Target
0  1.293226 -0.617362 -0.110447  -10.378660
1 -2.793085  0.366332  1.937529   25.512450
2  0.801861 -0.186570  0.046567   19.677056
3  0.129102  0.502741  1.616950  149.502054
4 -0.691661 -0.687173 -0.396754 -121.652109