In [1]:
import pymongo

In [2]:
from pymongo import MongoClient

In [3]:
client = MongoClient()

In [4]:
db = client.test

In [5]:
employee = db.employee

In [6]:
employee.drop()

In [8]:
# create new employee
employee = db.employee

In [9]:
mylist  = [{"_id":1,"name":"John","address":"Highway 37"},
                {"_id":2,"name":"Peter","address":"Lowstreet 27"},
                {"_id":3,"name":"Amy","address":"Apple st 652"},
                {"_id":4,"name":"Hannah","address":"Mountain 21"},
                {"_id":5,"name":"Michael","address":"Valley 345"},
                {"_id":6,"name": "Vicky", "address": "Yellow Garden 124"},
                {"_id":7,"name": "Nicky", "address": "Yellow Garden 123"}]


In [10]:
x = employee.insert_many(mylist)

print(x.inserted_ids)

[1, 2, 3, 4, 5, 6, 7]


In [11]:
client.list_database_names()

['admin', 'config', 'local', 'test']

In [12]:
db.list_collection_names()

['employee']

In [13]:
myquery = {'address': 'Highway 37'}
mydoc = employee.find(myquery)

for x in mydoc:
    print(x)

{'_id': 1, 'name': 'John', 'address': 'Highway 37'}


In [15]:
myquery = {'address': {'$regex': '^Y'}}
mydoc = employee.find(myquery)

for x in mydoc:
    print(x)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}


In [17]:
# Advanced query using 'OR'

myquery = {'$or': [
    {'address': {'$regex': '^Y'}},
    {'address': {'$regex': '^V'}}
]}

mydoc = employee.find(myquery)

for i in mydoc:
    print(i)

{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}


In [18]:
# ALternative using regex 
myquery = {'address': {'$regex': '^V|^Y'}}
mydoc = employee.find(myquery)

for i in mydoc:
    print(i)


{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}


In [19]:
employee.insert_one({"_id":8,"name":"Sunil","address":"Scarborough"})

In [21]:
myquery = {'address': {'$regex': '^S|^Y'}}
mydoc = employee.find(myquery)

for i in mydoc:
    print(i)


{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [22]:
myquery = {'$and': [
    {'address': {'$regex': '^Y'}},
    {'address': {'$regex': '1'}}
]}

mydoc = employee.find(myquery)
for x in mydoc:
    print(x)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}


In [23]:
myquery = {'$and': [
    {'address': {'$regex': '^Y'}},
    {'address': {'$regex': '1'}},
    {'name': {'$regex': '^N'}}
]}

mydoc = employee.find(myquery)
for x in mydoc:
    print(x)

{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}


In [24]:
myquery = {'$and': [
    {'address': {'$regex': '^Y'}},
    {'address': {'$regex': '1'}},
    {'name': {'$ne': 'Nicky'}}
]}

mydoc = employee.find(myquery)
for x in mydoc:
    print(x)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}


In [30]:
myquery = {'address': {'$gt': 'S'}}
mydoc = employee.find(myquery)

for x in mydoc:
    print(x)

{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [26]:
myquery = {'address': {'$lt': 'S'}}
mydoc = employee.find(myquery)

for x in mydoc:
    print(x)

{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}


In [32]:
myquery = {'address': {'$lte': 'S'}}
mydoc = employee.find(myquery)

for x in mydoc:
    print(x)

{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}


In [28]:
myquery = {'address': {'$gte': 'S'}}
mydoc = employee.find(myquery)

for x in mydoc:
    print(x)

{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [34]:
mydoc = employee.find().sort('name')

for x in mydoc:
    print(x)

{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}


In [35]:
mydoc = employee.find().sort('name', 1) #ascending

for x in mydoc:
    print(x)

{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}


In [36]:
mydoc = employee.find().sort('name', -1) #descending

for x in mydoc:
    print(x)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}


In [37]:
for x in employee.find():
    print(x)

myquery = {'address': 'Valley 345'}
newvalues = {'$set': {'address': 'Canyon 123'}}

employee.update_one(myquery, newvalues)

for x in employee.find():
    print(x)

{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [38]:
myquery = {'address': {'$regex': '^C'}}
newvalues = {'$set': {'name': 'Minnie'}}

x = employee.update_many(myquery, newvalues)

print(x.modified_count, 'documents updated.')

for x in employee.find():
    print(x)

1 documents updated.
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Minnie', 'address': 'Canyon 123'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [39]:
db.employee.delete_one({'Age': '35'})

In [40]:
db.employee.delete_one({'name': 'John'})

In [41]:
for i in employee.find():
    print(i)

{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Minnie', 'address': 'Canyon 123'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [42]:
myquery = {'address': 'Mountain 21'}
employee.delete_one(myquery)

In [43]:
for i in employee.find():
    print(i)

{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 5, 'name': 'Minnie', 'address': 'Canyon 123'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [44]:
myquery = {'address': {'$regex': '^A'}}

x = employee.delete_many(myquery)

print(x.deleted_count, 'documents deleted.')

1 documents deleted.


In [45]:
myquery = {'$or': [
    {'address': {'$regex': '^A'}},
    {'name': {'$regex': '^P'}}
]}

x = employee.delete_many(myquery)

print(x.deleted_count, 'documents deleted.')

1 documents deleted.


In [46]:
for i in employee.find():
    print(i)

{'_id': 5, 'name': 'Minnie', 'address': 'Canyon 123'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 123'}
{'_id': 8, 'name': 'Sunil', 'address': 'Scarborough'}


In [47]:
x = employee.delete_many({})
print(x.deleted_count, 'documents deleted')

4 documents deleted


In [48]:
employee.drop()

In [49]:
import numpy as np

In [50]:
vector_row = np.array([1, 2, 3])

In [51]:
vector = np.array([1, 2, 3, 4, 5, 6])

In [52]:
vector[2]

3

In [53]:
vector[-4]

3

In [63]:
def return_index(vector, val: list):
    vector_list = vector.tolist()
    for i in val:
        print(vector_list.index(i))

In [64]:
return_index(vector, [4, 6])

3
5


In [58]:
np.where(vector == 4)

(array([3]),)

In [65]:
vector[2:-1]

array([3, 4, 5])

In [66]:
vector[::2]

array([1, 3, 5])